### ISSUE TITLE
Horizontal Scrollbar on Windows and Linux

### ISSUE THREAD

**Issue by dance2die** [usereactnyc/usereact.nyc#30]
A horizontal scrollbar shows in any browser dimension (Tried it on FF & Chrome).

## Windows 10

![horizontal scroll bar on windows 10](https://user-images.githubusercontent.com/8465237/60021787-99085e00-9660-11e9-8402-e9e003a06f8c.png)

## Ubuntu (with KDE) 19.03

![horizontal scroll bar on Ubuntu](https://user-images.githubusercontent.com/8465237/60022237-6c087b00-9661-11e9-925b-b31896a41ac2.png)

You can see that the horizontal scrollbar appears on the bottom disabled on reisze.

![TtT40BFWsh](https://user-images.githubusercontent.com/8465237/60021888-cead4700-9660-11e9-94e2-62d2323a75c8.gif)

## Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Chrome Version 75.0.3770.100 (Official Build) (64-bit)
| Browser          | FireFox Quantum 67.0.4 (64-bit)
| Operating System | Windows 10 Build 1903
| Operating System | Ubuntu 19.03

**Comment by NickFoden** [comment]
There is a new build with gatsby js. That just got merged ! -> https://usereact.nyc/

**Comment by dance2die** [comment]
Hi @NickFoden The horizontal scrollbar still appears 😢

**Comment by NickFoden** [comment]
Ah good catch. That is some sort of outer container we need to remove padding/margin of.

**Comment by NickFoden** [comment]
set `overflow:hidden` to remove horizontal bars now but the < WhatIs /> section needs some TLC with the 3 buttons to not overflow.

**Comment by NickFoden** [comment]
**The eagle is in the nest. I repeat. The Eagle is in the nest.**

**Comment by NickFoden** [comment]
But @dance2die if you can take a look and see if this works for you as well.

**Comment by dance2die** [comment]
@NickFoden Superヽ(✿ﾟ▽ﾟ)ノ

Looks great on both Windows & KDE
