### ISSUE TITLE
Fix accessibility issues (reported by Axe)

### ISSUE THREAD

**Issue by dance2die** [usereactnyc/usereact.nyc#48]
# ✨ Enhancement Request

After a PR #44, I've noticed that there are still many accessibility (a11y) issues reported by [Axe](https://www.deque.com/axe/) (an a11y testing tool).

![accesibility issues reported by Axe](https://user-images.githubusercontent.com/8465237/60269848-3b248200-98bd-11e9-864c-777a7e9c88fe.png)

# 🤔 What needs to be done?

There are 58 issues in 6 categories

1. Elements must have sufficient color contrast (48 issues)
1. [ ] Images must have alternate text (4 issues)
1. [ ] Links must have discernible text (3 issues)
1. [ ] Zooming and scaling must not be disabled (1 issues)
1. [ ] Document must have one main landmark (1 issue)
1. [ ] All page content must be contained by landmarks (1 issue)

Because `1. Elements must have sufficient color contrast` depends on the theme color, maybe the rest can be addressed.

**Comment by NickFoden** [comment]
Nice work !

**Comment by dance2die** [comment]
Thank you, Nick~
