### ISSUE TITLE
Add a Parallax Effect to the Top NYC image

### ISSUE THREAD

**Issue by donavon** [usereactnyc/usereact.nyc#62]
see example here: https://www.equalrightsamendment.org/

this one is worth 1000 bonus points to whomever implements the PR

**Comment by NickFoden** [comment]
https://github.com/usereactnyc/usereact.nyc/pull/63 

Quick attempt. Having the bg image scroll at slower speed is next.

**Comment by donavon** [comment]
not parallax, but #63 looks great. closing.
