### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by donavon** [usereactnyc/usereact.nyc#8]
currently we have the stock CRA readme. we can do better than that

**Comment by matthew-gerstman** [comment]
Netlify badge

```
[![Netlify Status](https://api.netlify.com/api/v1/badges/805c38b8-da50-4cf0-8853-3db04f834ccb/deploy-status)](https://app.netlify.com/sites/priceless-meitner-a9781b/deploys)
```

**Comment by matthew-gerstman** [comment]
[![Netlify Status](https://api.netlify.com/api/v1/badges/805c38b8-da50-4cf0-8853-3db04f834ccb/deploy-status)](https://app.netlify.com/sites/priceless-meitner-a9781b/deploys)

**Comment by donavon** [comment]
```
![blazing fast](https://img.shields.io/badge/speed-blazing%20%F0%9F%94%A5-brightgreen.svg?style=flat-square)
```
![blazing fast](https://img.shields.io/badge/speed-blazing%20%F0%9F%94%A5-brightgreen.svg?style=flat-square)

**Comment by NickFoden** [comment]
Today got away from me. Started a rough draft. I think we can have some more fun with emojis and icons. Also the asset for the Meetup header as the main image could replace the one I cropped from the website.  

https://github.com/usereactnyc/usereact.nyc/blob/6b2bdf366b7d4680bd617d839a9922f1d954a69a/README.md

https://github.com/usereactnyc/usereact.nyc/pull/49

![image](https://user-images.githubusercontent.com/8321838/60310261-072e7880-9920-11e9-9c3d-7c710509bd2c.png)

**Comment by matthew-gerstman** [comment]
@donavon Can you let us know what else you were thinking (if anything)?

**Comment by donavon** [comment]
https://github.com/usereactnyc/usereact.nyc/pull/49 was pretty much what i was thinking

**Comment by matthew-gerstman** [comment]
Thanks everyone!
